export const songs = [
  {
    id: 1,
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Pop",
    duration: 200,
    plays: 1250000,
    releaseYear: 2020,
    audioUrl: "/songs/blinding-lights.mp3",
    coverImage: "https://picsum.photos/seed/afterhours/200",
    isExplicit: false,
  },
  {
    id: 2,
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    album: "DAMN.",
    genre: "Hip-Hop",
    duration: 177,
    plays: 3200000,
    releaseYear: 2017,
    audioUrl: "/songs/humble.mp3",
    coverImage: "https://picsum.photos/seed/damn/200",
    isExplicit: true,
  },
  {
    id: 3,
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    genre: "Pop",
    duration: 203,
    plays: 980000,
    releaseYear: 2021,
    audioUrl: "/songs/levitating.mp3",
    coverImage: "https://picsum.photos/seed/futurenostalgia/200",
    isExplicit: false,
  },
  {
    id: 4,
    title: "Take Five",
    artist: "Dave Brubeck",
    album: "Time Out",
    genre: "Jazz",
    duration: 324,
    plays: 450000,
    releaseYear: 1959,
    audioUrl: "/songs/take-five.mp3",
    coverImage: "https://picsum.photos/seed/timeout/200",
    isExplicit: false,
  },
  {
    id: 5,
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    genre: "Rock",
    duration: 301,
    plays: 2100000,
    releaseYear: 1991,
    audioUrl: "/songs/teen-spirit.mp3",
    coverImage: "https://picsum.photos/seed/nevermind/200",
    isExplicit: true,
  },
  {
    id: 6,
    title: "Bad Guy",
    artist: "Billie Eilish",
    album: "When We All Fall Asleep",
    genre: "Pop",
    duration: 194,
    plays: 1750000,
    releaseYear: 2019,
    audioUrl: "/songs/bad-guy.mp3",
    coverImage: "https://picsum.photos/seed/badguy/200",
    isExplicit: false,
  },
  {
    id: 7,
    title: "Lose Yourself",
    artist: "Eminem",
    album: "8 Mile",
    genre: "Hip-Hop",
    duration: 326,
    plays: 2900000,
    releaseYear: 2002,
    audioUrl: "/songs/lose-yourself.mp3",
    coverImage: "https://picsum.photos/seed/8mile/200",
    isExplicit: true,
  },
  {
    id: 8,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    genre: "Rock",
    duration: 354,
    plays: 4000000,
    releaseYear: 1975,
    audioUrl: "/songs/bohemian-rhapsody.mp3",
    coverImage: "https://picsum.photos/seed/queen/200",
    isExplicit: false,
  },
  {
    id: 9,
    title: "So What",
    artist: "Miles Davis",
    album: "Kind of Blue",
    genre: "Jazz",
    duration: 545,
    plays: 300000,
    releaseYear: 1959,
    audioUrl: "/songs/so-what.mp3",
    coverImage: "https://picsum.photos/seed/kindofblue/200",
    isExplicit: false,
  },
];
